---
- name: "Laboratorio de Delegacion de Servicios"
  hosts: nodo_01
  tasks:
    - name: "Registrar la hora actual del nodo"
      command: "date +%T"
      register: hora_actual

    - name: "Cambio de zona horaria"
      timezone:
        name: Europe/Moscow
      register: datos_zona_horaria

    - name: "Creacion de fichero de datos"
      file:
        path: "/tmp/datos_horarios_{{ ansible_facts['hostname'] }}.txt"
        state: touch
    
    - name: "Registrar la hora de Moscow"
      command: "date +%T"
      register: hora_moscow
    
    - name: "Insertar registros en el fichero"
      blockinfile:
        path: "/tmp/datos_horarios_{{ ansible_facts['hostname'] }}.txt"
        block: |
          La zona horaria antes del cambio es {{ datos_zona_horaria.diff.before.name }} y la hora es {{ hora_actual.stdout_lines }}
          La zona horaria despues del cambio es {{ datos_zona_horaria.diff.after.name }} y la hora es {{ hora_moscow.stdout_lines }}

    - name: "Volver a la zona horaria iniciarl"
      timezone:
        name: "{{ datos_zona_horaria.diff.before.name }}"

- name: "Segundo play para modificar la hora del nodo_02"
  hosts: nodo_02
  tasks:
    - name: "Registrar la hora actual del nodo"
      command: "date +%T"
      register: hora_actual

    - name: "Cambio de zona horaria"
      timezone:
        name: Asia/Tokyo
      register: datos_zona_horaria

    - name: "Creacion de fichero de datos"
      file:
        path: "/tmp/datos_horarios_{{ ansible_facts['hostname'] }}.txt"
        state: touch
    
    - name: "Registrar la hora de Tokio"
      command: "date +%T"
      register: hora_tokio
    
    - name: "Insertar registros en el fichero"
      blockinfile:
        path: "/tmp/datos_horarios_{{ ansible_facts['hostname'] }}.txt"
        block: |
          La zona horaria antes del cambio es {{ datos_zona_horaria.diff.before.name }} y la hora es {{ hora_actual.stdout_lines }}
          La zona horaria despues del cambio es {{ datos_zona_horaria.diff.after.name }} y la hora es {{ hora_tokio.stdout_lines }}

    - name: "Volver a la zona horaria iniciarl"
      timezone:
        name: "{{ datos_zona_horaria.diff.before.name }}"

    - copy:
        src: /tmp/datos_horarios_nodo_02.txt
        dest: /tmp/datos_horarios_nodo_02.txt
        remote_src: yes
      delegate_to: master

#   - name: "Descargarnos el fichero del nodo_02"
#     synchronize:
#       src: "/tmp/datos_horarios_nodo_02.txt"
#       dest: "/tmp/datos_horarios_nodo_02.txt"
#       mode: pull
#     delegate_to: master